### ISSUE TITLE
Nguyễn Vân Hải-15022851-N3-elementalheroneosazxx@gmail.com

### ISSUE THREAD

**Issue by 31121997azxxa** [UET-INT2204-11-fall-18/lab01-31121997azxxa#1]
public class HelloWorrld {
    public static void main(String[] args) {
         System.out.println("Hello World");  
    }
    
}

**Comment by tuantmtb** [comment]
Mình cần bạn commit file mã nguồn lên trên này. Không phải lên issues bạn nhé.
https://github.com/UET-INT2204-11-fall-18/lab01-31121997azxxa
